[HW3] Implement custom class loader for plugin loading
M4RFF/alab-java-hw pull request #3
Opened 2024-12-26 17:22 UTC by M4RFF

2024-12-26 17:25 UTC, M4RFF commented
@elnurmes, Hello! I made a mistake when I committed this assignment and accidentally named the main commit like
**_[HW2] Implement custom class loader for plugin loading_**, and additionally pushed other commits

2024-12-26 19:45 UTC, elnurmes requested changes
hi, added small comment, pls check it)

2024-12-26 19:45 UTC, elnurmes commented on src/hw3/CustomClassLoader.java
> +    @Override // overriding findClass to load class by name
remove this kind of comments)

2024-12-27 07:12 UTC, elnurmes approved these changes

2024-12-27 11:02 UTC, merged